### ISSUE TITLE
Having more than one institution connection.

### ISSUE THREAD

**Issue by guillelopez** [plaid/project-csa#11]
Hi there, after correctly adding an institution connection (Chase) using live bank account credentials, I tried to add another institution (Bank of America), this time using Plaid sandbox credentials. The new institution (Bank of America) has been added correctly, but then the plaid user's accounts information doesn't include any more any of my previous Chase accounts. I also noticed that my user token has changed to `test_bofa`.

Is this something expected as I am using real bank account credentials at the same time as the sandbox credentials? 

If I was using real bank account credentials my plaid user will still keep all the previous bank accounts as I add more banks?

Thanks.

**Comment by michaelckelly** [comment]
@guillelopez 

I'm not quite sure I understand your question - feel free to keep this going if I don't answer it!

Each user you add via Project CSA or one of the [add user](https://www.plaid.com/docs/#add-user) endpoints of the Plaid API (i.e. `POST /connect` and `POST /connect/step`) is a unique action.  That user is represented by a unique access token.  

The [demo](http://plaid.github.io/project-csa) does not "aggregate" accounts across user adds - each time you add a user, either with live credentials or sandbox ones, you'll see just the accounts associated with that particular user, not all of the accounts you've seen when using the demo.

**Comment by guillelopez** [comment]
Well, I was not refering to the demo. It was more a Plaid API user flow question. 

But I think now I see the point: Plaid API `POST /connect` doesn't provide the option to aggregate connections to existing users.

I don't know why I was expecting it to work that way.

I am trying to build a small app that consolidates all the bank accounts from different institutions, so I imagine will be building that aggregation functionality into my app.

Thanks @michaelckelly for your clarification.

**Comment by michaelckelly** [comment]
Ah I see, @guillelopez - yes the API does not handle aggregation logic such as that, but sounds like a cool app nonetheless!

**Comment by sharavsambuu** [comment]
aggregation feature useful for our app too. So how to achieve this kind of functionalities?
