### ISSUE TITLE
Set data attributes after script load

### ISSUE THREAD

**Issue by c316** [plaid/project-csa#12]
Is it possible to set the data attributes after the script has loaded? I'm using a framework (Meteor) that doesn't make it very easy to use the script as it is currently shown on the Readme example. I have it working, but not for my mobile sessions and I'd really like to narrow down why this is. 

Stripe has a good example of what I'm talking about in their Stripe.js file. 
https://stripe.com/docs/stripe.js

Include the script, 

    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

Then set your key

    Stripe.setPublishableKey('YOUR_PUBLISHABLE_KEY');

**Comment by michaelckelly** [comment]
@c316:

Yes, the ability to manually set the parameters (as opposed to via `data-*` attributes) is absolutely coming!  Look for that to be pushed out within the next week or two.

We'll be sure to update the [README][1] when that happens.

Thanks for the feedback - keep it coming!

[1]: https://github.com/plaid/project-csa/blob/master/README.md
