### ISSUE TITLE
Load without button press

### ISSUE THREAD

**Issue by c316** [plaid/project-csa#13]
In my app the flow would be better if I could trigger the CSA load without a button press. I know I can trigger the button press programmatically too. I think this would be a nice feature. 

By the way, good work, this has already saved me a lot of time and work.  It looks great and works great.

**Comment by michaelckelly** [comment]
Moving this to https://github.com/plaid/project-csa/issues/17.

**Comment by benissimo** [comment]
@michaelckelly I think this issue should be re-opened. Please see recent comments on #17
