### ISSUE TITLE
Choose which orgs show in the list

### ISSUE THREAD

**Issue by c316** [plaid/project-csa#14]
It would be nice to be able to limit the options in the list of orgs based on what kinds of accounts they can contain. 

For instance, I want the users to setup a checking account link and as far as I can tell not all of these institutions have checking accounts so I wouldn't want to show those institutions. I'd even settle for just being able to set which institutions show up, then I can accomplish the same thing manually.

**Comment by michaelckelly** [comment]
@c316 I've consolidated this and a few other issues to https://github.com/plaid/project-csa/issues/17.
