### ISSUE TITLE
Provide the "none of the above" case

### ISSUE THREAD

**Issue by brendan-peerstreet** [plaid/project-csa#15]
The UI doesn't seem to support the case where the user wants to use an account that is not at one of the supported institutions.  

Our use is case is that we want to gather the users account / routing number.  Plaid is as an alternative to the user manually inputting that information.  So for us, we'd like them to see the list of institutions, and be able to say that their institution is not on the list, or that they prefer to provide the info manually.

**Comment by michaelckelly** [comment]
@brendan-peerstreet 

This is definitely a feature we're planning - look for it to be rolled out within the next two weeks.

In general, you'll be to provide your own view/page for selecting an institution - you can then trigger Project CSA when a Plaid-supported institution is selected (and jump directly to that institution's login view, not the "Pick an Institution" page) or your own business logic / account & routing aggregation when another institution is selected.  This will be done through vanilla JavaScript.  

We'll include code samples and demos for this as well.

**Comment by michaelckelly** [comment]
Moving this to https://github.com/plaid/project-csa/issues/17.
