### ISSUE TITLE
Returning 401 Unauthorized and/or corrupted tokens

### ISSUE THREAD

**Issue by robbfitzsimmons** [plaid/project-csa#16]
Hi folks,

As of this weekend this module was returning access_tokens that gave a `1105 bad_access_token: This access token appears to be corrupted` response.

As of this morning is simply failing with a 401 Unauthorized in the console (with no end-user error message, just a progress bar stallout).

Not sure if this is affecting only my account or your users more generally (also emailed support this weekend), but any help would be appreciated.

Robb

**Comment by robbfitzsimmons** [comment]
Closing the issue for now as I realize there was an error in which access_token I was saving (maybe naming these two tokens more distinctly would be good?).

Still returning a 401 for public token 05ce79045224ebbdb0e6e937a5bf62. Help on that would be great!

**Comment by michaelckelly** [comment]
We'll take a look at that shortly @robfitzsimmons. Thanks for letting us know. 

Thanks for the feedback as well - project CSA is still evolving. Our goal is to make it straightforward and simple to get going - sounds like we still have some work to do on that front!

**Comment by michaelckelly** [comment]
@robbfitzsimmons 

The 401s you were seeing were due to your client id being over the initial user add limit on the API.  I've opened an issue internally to ensure that we present a better error in this case as opposed to hanging.  You should be all set now!

**Comment by robbfitzsimmons** [comment]
@michaelckelly thanks for that! I've corrected the issue with the initial add limit with your team, but actually still seeing the 401, both with my public token as well as the test-key setup.

![screen shot 2015-04-20 at 12 48 19 pm](https://cloud.githubusercontent.com/assets/686720/7235335/9ecc779e-e75b-11e4-9ffa-652f24ab77f4.png)

**Comment by michaelckelly** [comment]
I've looked through our logs and am not seeing any 401s from your public key but am seeing 401s with `test-key` as the `data-key` attribute value.  That should be `test_key`, with an `_` as opposed to a `-`.

**Comment by robbfitzsimmons** [comment]
@michaelckelly ugh, thanks. Apologies for that typo. Working through logging on my end as well. I've got the step working on sandbox now and will keep stepping through with my real credentials. Will update if I hit additional snags.
