### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by pbernasconi** [plaid/project-csa#18]
Are you planning on supporting the mobile environment?

Using CSA on my iPhone results in an almost unusable interface, where the popup-modal is too small to interact with.

**Comment by michaelckelly** [comment]
@pbernasconi 

Yes we will be supporting mobile in the coming weeks - we have a few "features" that are in the pipeline listed under the "Expansion" section of the [README](https://github.com/plaid/project-csa/blob/master/README.md), including mobile support, but that's clearly not the best way to share that information.  I'll open an issue for this.

**Comment by pbernasconi** [comment]
That's my bad, I didn't remember that it was mentioned there.

**Comment by michaelckelly** [comment]
No worries - we appreciate the feedback!  Keep it coming! :)
