### ISSUE TITLE
Invalid public key in tartan

### ISSUE THREAD

**Issue by guillelopez** [plaid/project-csa#23]
Hi there,

I am getting an `{"error":"Invalid public_key"}` when using: 
```javascript
<form id="plaid-connect" method="POST" action="/connections"></form>
<script
  src="https://cdn.plaid.com/connect/beta/connect-initialize.js"
  data-client-name="Sssaving"
  data-form-id="plaid-connect"
  data-key="03ad5ef6e2aef1c3e061865d304428"
  data-product="connect"
  data-env="tartan">
</script>
```
If instead of `data-env="tartan"` I change it to `data-env="production"`, then it works fine.

Am I missing something?

**Comment by michaelckelly** [comment]
@guillelopez

Well look into this and get back to you shortly - thanks for getting in touch.

**Comment by michaelckelly** [comment]
@guillelopez You should be all set - that was an inadvertent error on our end.  Let me know if you run into any other issues with your `public_key`.

**Comment by guillelopez** [comment]
:ok_hand: 

It's working now. 
Thanks @michaelckelly.
