### ISSUE TITLE
Access Denied to connect-initialize.js

### ISSUE THREAD

**Issue by guillelopez** [plaid/project-csa#5]
Hi, I am getting an `AccessDenied` code when accessing `https://cdn.plaid.com/connect/latest/connect-initialize.js`.

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>EAF538568477838A</RequestId><HostId>IQTC2guxblQJ80pPOErpT5GiTdtw2TgMq0bf+w/p4xrKtNb8AkNZ3B59qQZ46ajtaBLFk8tVRhE=</HostId></Error>
```

I was trying as well with `https://cdn.plaid.com/connect/stable/connect-initialize.js` but then I don't have access to: `connect-initialize.js.map` and `connect.js.map`.

**Comment by whockey** [comment]
Definitely an issue on our side - we're checking it out right now.

**Comment by michaelckelly** [comment]
@guillelopez Sorry about that, typo on our end.  Fixing now.

**Comment by guillelopez** [comment]
:+1:
