### ISSUE TITLE
American Express support

### ISSUE THREAD

**Issue by robbfitzsimmons** [plaid/project-csa#8]
Looks great and having just integrated "the old way," this is worlds better.

What's going on with Amex? Any timeline for support?

Thanks,
Robb

**Comment by michaelckelly** [comment]
@robbfitzsimmons 

The demo is set up with `data-product="auth"` and we do not support auth for Amex.  If you change `data-product` to "connect", Amex will be enabled (although Fidelity, Schwab, and Capone360 will be disabled).

We'll be releasing a better solution than simply "graying out" certain institutions soon!

**Comment by robbfitzsimmons** [comment]
Ah, got it. Thanks! Closing.
